//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyForJob
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public string ApplicantId { get; set; }
        public string Message { get; set; }
        public string CV { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetUser Applicant { get; set; }
        public virtual Job Job { get; set; }
    }
}
